(()=>{
'use strict';
const subjects={Physics:['Electric Charges and Fields','Electrostatic Potential and Capacitance','Current Electricity','Moving Charges and Magnetism','Magnetism and Matter','Electromagnetic Induction','Alternating Current','Electromagnetic Waves','Ray Optics and Optical Instruments','Wave Optics','Dual Nature of Radiation and Matter','Atoms','Nuclei','Semiconductor Electronics'],Chemistry:['Solutions','Electrochemistry','Chemical Kinetics','d- and f-Block Elements','Coordination Compounds','Haloalkanes and Haloarenes','Alcohols, Phenols and Ethers','Aldehydes, Ketones and Carboxylic Acids','Amines','Biomolecules, Polymers and Chemistry in Everyday Life'],Mathematics:['Relations and Functions','Inverse Trigonometric Functions','Matrices','Determinants','Continuity and Differentiability','Application of Derivatives','Integrals','Application of Integrals','Differential Equations','Vector Algebra','Three Dimensional Geometry','Linear Programming','Probability']};
const KEY='discipline_ai_pyq_min_v1';const $=id=>document.getElementById(id);const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let saved=[];try{saved=JSON.parse(localStorage.getItem(KEY)||'[]')}catch(e){saved=[]}let current=null,index=0,answers=[],timer=null,seconds=0,pyqPrefill=null;
function save(){try{localStorage.setItem(KEY,JSON.stringify(saved))}catch(e){}}
function page(title,sub,body){return `<section class="page active"><div class="eyebrow">Sajid Khan • Class 12</div><h1 class="title">${title}</h1><p class="sub">${sub}</p>${body}</section>`}
function layout(){return `<aside class="side" id="side"><div class="brand"><div class="logo">✦</div>PYQ Study</div><nav class="nav"><button type="button" data-page="pyq">📚&nbsp; PYQ Test</button></nav></aside><main class="main"><div class="top"><button type="button" class="mobile" id="menuBtn">☰</button><div></div></div><div id="pages"></div></main>`}
function pyqPage(){return page('PYQ Test','Apna PYQ photo/PDF upload karo. AI usse MCQ test banayega, phir result ka AI analysis milega.',`<div class="card form"><div class="row"><label><span class="label">Subject</span><select id="subject" class="select">${Object.keys(subjects).map(s=>`<option>${s}</option>`).join('')}</select></label><label><span class="label">Chapter</span><select id="chapter" class="select"></select></label></div><label><span class="label">PYQ Photos / PDF</span><input id="files" class="input" type="file" accept="image/*,.pdf" multiple><small class="muted">Maximum 12 files, each up to 15 MB.</small></label><label><span class="label">Optional manual questions</span><textarea id="manual" class="input" rows="5" placeholder="Questions yahan paste kar sakte ho..."></textarea></label><div class="row"><label><span class="label">Timer</span><input id="mins" class="input" type="number" min="1" max="180" value="15"></label><label><span class="label">Questions</span><select id="count" class="select"><option value="all">All</option><option>10</option><option>20</option><option>30</option><option>50</option><option>100</option></select></label></div><div id="status" class="muted"></div><button id="read" class="btn">🤖 Read PYQ & Start Test</button></div><div class="card" style="margin-top:15px"><h3>Saved PYQ</h3>${saved.length?saved.slice().reverse().map((p,i)=>`<div class="chapter"><span><b>${esc(p.name)}</b><br><small class="muted">${p.questions.length} questions</small></span><button class="btn secondary saved" data-i="${saved.length-1-i}">Start</button></div>`).join(''):'<div class="empty">Abhi koi PYQ saved nahi hai.</div>'}</div>`)}
function fill(){const s=$('subject')?.value;if(!$('chapter'))return;$('chapter').innerHTML=(subjects[s]||[]).map(c=>`<option>${esc(c)}</option>`).join('')}
function file64(f){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result).split(',')[1]||'');r.onerror=rej;r.readAsDataURL(f)})}
async function read(){const fs=[...($('files')?.files||[])],text=$('manual')?.value?.trim(),subject=$('subject').value,chapter=$('chapter').value,status=$('status'),btn=$('read');if(!chapter){status.textContent='⚠️ Chapter select karo.';return}if(!fs.length&&!text){status.textContent='⚠️ PYQ photo/PDF upload ya questions paste karo.';return}if(fs.length>12||fs.some(f=>f.size>15*1024*1024)){status.textContent='⚠️ Maximum 12 files, each 15 MB.';return}btn.disabled=true;status.textContent='⏳ AI PYQ read kar raha hai...';try{const files=await Promise.all(fs.map(async f=>({name:f.name,mimeType:f.type||'application/octet-stream',data:await file64(f)})));const r=await fetch('/api/pyq-test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({files,text,subject,chapter})});const d=await r.json();if(!r.ok)throw Error(d.error||'PYQ processing failed');if(!Array.isArray(d.questions)||!d.questions.length)throw Error('MCQ questions nahi mile.');const n=$('count').value;const qs=n==='all'?d.questions:d.questions.slice(0,Number(n));const p={id:'p'+Date.now(),name:`${subject} — ${chapter}`,subject,chapter,questions:qs,date:new Date().toISOString()};saved.push(p);save();start(p,Number($('mins').value)||15);status.textContent=`✅ ${qs.length} questions ready.`}catch(e){status.textContent='❌ '+(e.message||'Error');btn.disabled=false}}
function start(p,mins){current=p;index=0;answers=[];seconds=mins*60;clearInterval(timer);renderQuestion();timer=setInterval(()=>{seconds--;updateTimer();if(seconds<=0){clearInterval(timer);finish(true)}},1000)}
function updateTimer(){const t=$('timer');if(t)t.textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`}
function renderQuestion(){if(!current)return;const q=current.questions[index],opts=Array.isArray(q.options)?q.options:[];$('pages').innerHTML=page('PYQ Test',`${esc(current.subject)} • ${esc(current.chapter)}`,`<div class="card test"><div class="testhead"><b>Question ${index+1} / ${current.questions.length}</b><span class="timer" id="timer"></span></div><div class="question">${esc(q.text||q.question||'')}</div><div class="options">${opts.map((o,i)=>`<button type="button" class="option ${answers[index]===i?'selected':''}" data-opt="${i}">${String.fromCharCode(65+i)}. ${esc(o)}</button>`).join('')}</div><div class="footer"><button class="btn secondary" id="prev" ${index?'':'disabled'}>← Previous</button><button class="btn" id="next">${index===current.questions.length-1?'Submit Test':'Next →'}</button></div></div>`);updateTimer();document.querySelectorAll('[data-opt]').forEach(b=>b.onclick=()=>{answers[index]=Number(b.dataset.opt);renderQuestion()});$('prev').onclick=()=>{if(index>0){index--;renderQuestion()}};$('next').onclick=()=>{if(index===current.questions.length-1)finish(false);else{index++;renderQuestion()}}}
function correctIndex(q){let a=q.answer??q.answerIndex??q.correctAnswer??q.correct;if(typeof a==='number')return a;if(typeof a==='string'){const s=a.trim().toUpperCase();if(/^[A-Z]$/.test(s))return s.charCodeAt(0)-65;const n=Number(s);if(Number.isInteger(n))return n}return -1}
function finish(auto){clearInterval(timer);let score=0;current.questions.forEach((q,i)=>{if(answers[i]===correctIndex(q))score++});const total=current.questions.length,pct=Math.round(score*100/Math.max(1,total));const t={subject:current.subject,chapter:current.chapter,questions:current.questions,answers:answers,score,total,percent:pct,elapsed:Math.max(0,15*60-seconds),date:new Date().toISOString()};showResult(t,auto)}
function showResult(t,auto){$('pages').innerHTML=page('PYQ Result',`${esc(t.subject)} • ${esc(t.chapter)}`,`<div class="card center"><div class="score">${t.percent}%</div><h2>${t.score} / ${t.total}</h2><p class="muted">${auto?'Time khatam ho gaya.':'Test submitted successfully.'}</p><div class="actions" style="justify-content:center"><button class="btn" id="analyze">🤖 Analyze with AI</button><button class="btn secondary" id="again">🔄 Try Again</button><button class="btn ghost" id="back">📚 PYQ Test</button></div><div id="analysis"></div></div>`);$('analyze').onclick=()=>analyze(t);$('again').onclick=()=>start(current,15);$('back').onclick=()=>show('pyq')}
async function analyze(t){const b=$('analyze'),box=$('analysis');b.disabled=true;b.textContent='⏳ AI analyzing...';box.innerHTML='<div class="card" style="margin-top:15px">AI tumhare answers aur weak concepts analyze kar raha hai...</div>';try{const rows=t.questions.map((q,i)=>({no:i+1,question:q.text||q.question,options:q.options,correct:correctIndex(q),student:t.answers[i]??null}));const prompt=`Analyze this Class 12 Bihar Board PYQ test in simple Hinglish. Do not invent facts. Give score summary, weak concepts based only on supplied data, question numbers to revise, and a 3-step improvement plan. Subject: ${t.subject}. Chapter: ${t.chapter}. Score: ${t.score}/${t.total} (${t.percent}%). Data: ${JSON.stringify(rows).slice(0,50000)}`;const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:[{role:'user',content:prompt}]})});const d=await r.json();if(!r.ok)throw Error(d.error||'AI analysis failed');box.innerHTML=`<div class="card" style="margin-top:15px"><h3>🤖 AI Analysis</h3><div style="line-height:1.7;white-space:pre-wrap">${esc(d.reply||'Analysis nahi mila.')}</div></div>`;b.textContent='🔄 Re-analyze';b.disabled=false}catch(e){box.innerHTML=`<div class="card" style="margin-top:15px"><b>⚠️ Analysis unavailable</b><p>${esc(e.message||'Try again')}</p></div>`;b.textContent='🤖 Analyze with AI';b.disabled=false}}
function show(id){if(id==='pyq'){pyqPrefill=null;$('pages').innerHTML=pyqPage();fill();$('subject').onchange=fill;$('read').onclick=read;document.querySelectorAll('.saved').forEach(b=>b.onclick=()=>start(saved[Number(b.dataset.i)],15));}else if(id==='routine'){if(typeof window.openRoutine==='function')window.openRoutine()}}
window.show=show;window.showResult=showResult;document.addEventListener('click',e=>{const b=e.target.closest?.('[data-page]');if(b){e.preventDefault();show(b.dataset.page)}});document.addEventListener('DOMContentLoaded',()=>{document.getElementById('root').innerHTML=layout();show('pyq')});if(document.readyState!=='loading'){document.getElementById('root').innerHTML=layout();show('pyq')}
})();
