(()=>{
const ROUTINE_KEY='discipline_ai_day_routine_v2';
const oldKey='discipline_ai_day_routine_v1';
const localDate=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const prettyDate=k=>{const d=new Date(`${k}T00:00:00`);return d.toLocaleDateString('en-IN',{weekday:'short',day:'2-digit',month:'short',year:'numeric'})};
const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const defaults=[
{id:'1',time:'10:00',end:'10:30',task:'English previous chapter revision',subject:'English',mins:30},
{id:'2',time:'10:30',end:'11:30',task:'English core study',subject:'English',mins:60},
{id:'3',time:'11:35',end:'12:00',task:'Math previous chapter revision',subject:'Math',mins:25},
{id:'4',time:'12:00',end:'13:30',task:'Math core chapter study',subject:'Math',mins:90},
{id:'5',time:'13:30',end:'14:00',task:'Lunch',subject:'Break',mins:0,break:true},
{id:'6',time:'14:00',end:'14:15',task:'Physics previous day / chapter revision',subject:'Physics',mins:15},
{id:'7',time:'14:15',end:'16:00',task:'Physics core study',subject:'Physics',mins:105},
{id:'8',time:'16:00',end:'16:20',task:'Chemistry previous chapter / day revision',subject:'Chemistry',mins:20},
{id:'9',time:'16:20',end:'18:00',task:'Chemistry core study',subject:'Chemistry',mins:100},
{id:'10',time:'18:20',end:'18:30',task:'Revision',subject:'Revision',mins:10},
{id:'11',time:'18:30',end:'19:30',task:'Physics Chapter 3',subject:'Physics',mins:60}
];
function load(){try{let x=JSON.parse(localStorage.getItem(ROUTINE_KEY)||'null');if(x&&Array.isArray(x.items))return x;const old=JSON.parse(localStorage.getItem(oldKey)||'null');if(old&&Array.isArray(old.items))return {items:defaults,done:old.done||{},history:old.history||{}};return {items:defaults,done:{},history:{}}}catch{return {items:defaults,done:{},history:{}}}}
function save(x){localStorage.setItem(ROUTINE_KEY,JSON.stringify(x))}
function getTests(){try{return JSON.parse(localStorage.getItem('discipline_ai_tests_v4')||'[]')}catch{return []}}
function ensure(x,key){x.done=x.done||{};x.done[key]=x.done[key]||{};x.history=x.history||{};if(!x.history[key])x.history[key]={date:key,items:{},studyMins:0};return x}
function dayStats(x,key){ensure(x,key);const items=x.items||[],done=items.filter(i=>!i.break&&x.done[key]?.[i.id]).length,planned=items.filter(i=>!i.break).reduce((a,i)=>a+(Number(i.mins)||0),0),study=items.filter(i=>!i.break&&x.done[key]?.[i.id]).reduce((a,i)=>a+(Number(i.mins)||0),0),total=items.filter(i=>!i.break).length,pct=total?Math.round(done/total*100):0,tests=getTests().filter(t=>String(t.date||'').slice(0,10)===key),avg=tests.length?Math.round(tests.reduce((a,t)=>a+(Number(t.percent)||0),0)/tests.length):0;return {done,total,planned,study,pct,tests,avg}}
function historyStats(x,key){const s=dayStats(x,key),h=x.history?.[key];return {...s,study:Number(h?.studyMins??s.study),completed:s.done}}
function recordHistory(x,key){const s=dayStats(x,key);x.history=x.history||{};x.history[key]={date:key,items:{...(x.done[key]||{})},studyMins:s.study,plannedMins:s.planned,completed:s.done,total:s.total,progress:s.pct}}
function routinePage(){const x=getState(),key=localDate(),s=dayStats(x,key),rows=(x.items||[]).map(i=>`<div class="routine-item ${i.break?'break-item ':''}${x.done[key]?.[i.id]?'done':''}"><label class="routine-check"><input type="checkbox" data-routine="${esc(i.id)}" ${x.done[key]?.[i.id]?'checked':''}><span></span></label><div class="routine-time">${esc(i.time)}–${esc(i.end)}</div><div class="routine-info"><b>${esc(i.task)}</b><small>${esc(i.subject)}${i.mins?' • '+Number(i.mins)+' min':''}${i.break?' • Break':''}</small></div></div>`).join('');return page('My Day Routine','Tumhara handwritten daily study schedule + date-wise progress tracker.',`<div class="routine-hero card"><div><div class="eyebrow">${esc(prettyDate(key))}</div><h2 style="margin:4px 0">My Daily Study Routine</h2><p class="muted">Har study block complete hone par tick karo. Progress aur date-wise history automatically save hogi.</p></div><div class="routine-circle" style="--routine-p:${s.pct}%"><strong>${s.pct}%</strong><span>Today</span></div></div><div class="grid stats routine-stats"><div class="card stat"><span>Study Blocks</span><b>${s.done}/${s.total}</b></div><div class="card stat"><span>Study Completed</span><b>${s.study} min</b></div><div class="card stat"><span>Planned Study</span><b>${s.planned} min</b></div><div class="card stat"><span>Tests Today</span><b>${s.tests.length} • ${s.avg}%</b></div></div><div class="card"><div class="section"><div><h3>📅 Today's Schedule</h3><p class="muted" style="margin:3px 0">Exact routine from your study schedule.</p></div><button type="button" class="btn secondary" id="editRoutine">✏️ Edit Routine</button></div><div class="routine-list">${rows}</div></div><div class="card routine-summary"><div class="section"><div><h3>📊 Today's Progress</h3><p class="muted">${s.done} of ${s.total} study blocks completed</p></div><b>${s.pct}%</b></div><div class="progress"><i style="width:${s.pct}%"></i></div><p><b>${s.study} min</b> study completed out of <b>${s.planned} min</b> planned.</p>${s.pct===100?'<div class="success-box">🔥 Aaj ka study routine complete!</div>':'<div class="muted">🎯 Remaining blocks complete karo aur progress update hoti rahegi.</div>'}</div><div class="card"><div class="section"><div><h3>📈 Day-wise & Date-wise Progress</h3><p class="muted">Kis date ko kitna study aur kitna routine complete hua.</p></div><button type="button" class="btn ghost" id="refreshHistory">↻ Refresh</button></div><div id="routineHistory">${historyHtml(x)}</div></div>`)}
function getState(){const x=load();return ensure(x,localDate())}
function bindRoutine(){const x=getState(),key=localDate();document.querySelectorAll('[data-routine]').forEach(cb=>cb.addEventListener('change',()=>{x.done[key]=x.done[key]||{};if(cb.checked)x.done[key][cb.dataset.routine]=true;else delete x.done[key][cb.dataset.routine];recordHistory(x,key);save(x);show('routine')}));document.getElementById('editRoutine')?.addEventListener('click',openEditor);document.getElementById('refreshHistory')?.addEventListener('click',()=>show('routine'))}
function historyHtml(x){const keys=new Set(Object.keys(x.history||{}));Object.keys(x.done||{}).forEach(k=>keys.add(k));keys.add(localDate());const arr=[...keys].sort().reverse().slice(0,31);return `<div class="history-list">${arr.map(k=>{const s=historyStats(x,k);return `<div class="history-row"><div><b>${esc(prettyDate(k))}</b><small>${s.done}/${s.total} study blocks • ${s.study} min study</small></div><div class="history-right"><b>${s.pct}%</b><div class="mini-progress"><i style="width:${s.pct}%"></i></div><small>${s.tests.length} test${s.tests.length===1?'':'s'} • avg ${s.avg}%</small></div></div>`}).join('')}</div>`}
function openEditor(){const old=document.getElementById('routineEditor');if(old)old.remove();const x=getState(),modal=document.createElement('div');modal.id='routineEditor';modal.className='routine-modal';modal.innerHTML=`<div class="routine-modal-box"><div class="section"><div><h2 style="margin:0">✏️ My Daily Routine</h2><p class="muted">Tumhare schedule ke time, subject, task aur duration yahan edit kar sakte ho.</p></div><button type="button" class="btn ghost" id="closeRoutine">✕</button></div><div id="routineEditRows">${x.items.map(editRow).join('')}</div><div class="actions"><button type="button" class="btn secondary" id="addRoutine">＋ Add Study Block</button><button type="button" class="btn" id="saveRoutine">💾 Save Routine</button></div></div>`;document.body.appendChild(modal);modal.querySelector('#closeRoutine').onclick=()=>modal.remove();modal.querySelector('#addRoutine').onclick=()=>{const c=modal.querySelector('#routineEditRows');c.insertAdjacentHTML('beforeend',editRow({id:'r'+Date.now(),time:'20:00',end:'20:30',task:'New Study Block',subject:'Study',mins:30}));bindDelete(modal)};modal.querySelector('#saveRoutine').onclick=()=>{x.items=[...modal.querySelectorAll('.routine-edit-row')].map(r=>({id:r.dataset.id||'r'+Math.random().toString(36).slice(2),time:r.querySelector('.rt-time').value||'00:00',end:r.querySelector('.rt-end').value||'00:30',task:r.querySelector('.rt-task').value.trim()||'Study Block',subject:r.querySelector('.rt-sub').value.trim()||'Study',mins:r.querySelector('.rt-break').checked?0:Math.max(1,Number(r.querySelector('.rt-mins').value)||30),break:r.querySelector('.rt-break').checked}));save(x);modal.remove();show('routine');toast('Daily routine saved. ✅')};bindDelete(modal)}
function bindDelete(m){m.querySelectorAll('.rt-del').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='1';b.onclick=()=>b.closest('.routine-edit-row').remove()})}
function editRow(i){return `<div class="routine-edit-row" data-id="${esc(i.id)}"><input class="input rt-time" type="time" value="${esc(i.time)}"><input class="input rt-end" type="time" value="${esc(i.end||'')}"><input class="input rt-task" placeholder="Task" value="${esc(i.task)}"><input class="input rt-sub" placeholder="Subject" value="${esc(i.subject)}"><input class="input rt-mins" type="number" min="0" max="600" value="${Number(i.mins)||0}"><label class="rt-break-label"><input class="rt-break" type="checkbox" ${i.break?'checked':''}> Break</label><button type="button" class="btn ghost rt-del">🗑️</button></div>`}
function addNav(){const nav=document.querySelector('.nav');if(nav&&!nav.querySelector('[data-page="routine"]')){const b=document.createElement('button');b.type='button';b.dataset.page='routine';b.innerHTML='📅&nbsp; My Day Routine';b.onclick=()=>show('routine');nav.appendChild(b)}}
const style=document.createElement('style');style.textContent=`.routine-hero{display:flex;justify-content:space-between;align-items:center;gap:18px;background:linear-gradient(135deg,#111a31,#0b1221)}.routine-circle{width:120px;height:120px;min-width:120px;border-radius:50%;display:grid;place-items:center;position:relative;background:conic-gradient(var(--p) var(--routine-p),#27314a 0)}.routine-circle:after{content:'';position:absolute;inset:9px;border-radius:50%;background:#0c1425}.routine-circle strong{position:relative;z-index:1;font-size:28px}.routine-circle span{position:absolute;z-index:1;font-size:10px;color:var(--muted);margin-top:48px}.routine-list{display:grid;gap:8px}.routine-item{display:grid;grid-template-columns:30px 105px 1fr;align-items:center;gap:8px;padding:12px;border-radius:12px;border:1px solid rgba(255,255,255,.08);background:rgba(255,255,255,.02)}.routine-item.done{opacity:.62}.routine-item.done .routine-info b{text-decoration:line-through}.break-item{opacity:.8}.routine-check input{display:none}.routine-check span{display:block;width:20px;height:20px;border:2px solid #68738d;border-radius:6px}.routine-check input:checked+span{background:var(--p);border-color:var(--p);position:relative}.routine-check input:checked+span:after{content:'✓';position:absolute;left:3px;top:-3px;font-weight:900}.routine-time{font-weight:800;font-size:12px}.routine-info small{display:block;color:var(--muted);margin-top:3px}.success-box{margin-top:10px;padding:10px;border-radius:10px;background:rgba(36,209,139,.1)}.history-list{display:grid;gap:8px}.history-row{display:flex;justify-content:space-between;gap:15px;align-items:center;padding:12px;border:1px solid rgba(255,255,255,.08);border-radius:12px}.history-row small{display:block;color:var(--muted);margin-top:4px}.history-right{text-align:right;min-width:150px}.mini-progress{height:6px;background:#202a40;border-radius:99px;overflow:hidden;margin:5px 0}.mini-progress i{display:block;height:100%;background:linear-gradient(90deg,var(--p),#2dd4ff);border-radius:99px}.routine-modal{position:fixed;inset:0;background:rgba(0,0,0,.75);z-index:10000;display:flex;align-items:center;justify-content:center;padding:15px}.routine-modal-box{width:min(1050px,100%);max-height:90vh;overflow:auto;background:#0c1425;border:1px solid rgba(255,255,255,.12);border-radius:18px;padding:18px}.routine-edit-row{display:grid;grid-template-columns:95px 95px 1.5fr 1fr 75px 70px 45px;gap:7px;margin-bottom:8px;align-items:center}.rt-break-label{font-size:12px;color:var(--muted)}@media(max-width:700px){.routine-hero{align-items:flex-start}.routine-circle{width:95px;height:95px;min-width:95px}.routine-item{grid-template-columns:30px 92px 1fr}.history-row{align-items:flex-start}.history-right{min-width:110px}.routine-edit-row{grid-template-columns:1fr 1fr}.routine-edit-row .rt-task,.routine-edit-row .rt-sub{grid-column:span 2}.routine-edit-row .rt-break-label{grid-column:span 2}}`;document.head.appendChild(style);
const oldShow=typeof show==='function'?show:null;if(oldShow)show=function(id){if(id==='routine'){const p=document.getElementById('pages');if(p){p.innerHTML=routinePage();bindRoutine()}return}return oldShow(id)};
setTimeout(addNav,300);setTimeout(addNav,1000);
})();
