(()=>{
const KEY='discipline_ai_day_routine_v5';
const pad=n=>String(n).padStart(2,'0');
const keyOf=(d=new Date())=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const fromKey=k=>{const [y,m,d]=k.split('-').map(Number);return new Date(y,m-1,d)};
const addDays=(k,n)=>{const d=fromKey(k);d.setDate(d.getDate()+n);return keyOf(d)};
const pretty=k=>fromKey(k).toLocaleDateString('en-IN',{weekday:'long',day:'2-digit',month:'short',year:'numeric'});
const time12=t=>{const [h,m]=String(t||'00:00').split(':').map(Number),ap=h>=12?'PM':'AM',hh=h%12||12;return `${hh}:${pad(m)} ${ap}`};
const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const minutesNow=()=>{const d=new Date();return d.getHours()*60+d.getMinutes()};
const blockState=i=>{if(i.break)return 'break';const [sh,sm]=String(i.time||'00:00').split(':').map(Number),[eh,em]=String(i.end||i.time||'00:00').split(':').map(Number),now=minutesNow(),start=sh*60+sm,end=eh*60+em;return now<start?'upcoming':now>=end?'expired':'live'};
const stateText=s=>s==='live'?'🟢 Live now':s==='upcoming'?'🔒 Not started':'⏰ Time over';
const defaults=[
{id:'1',time:'10:00',end:'10:30',task:'English previous chapter revision',subject:'English',mins:30},
{id:'2',time:'10:30',end:'11:30',task:'English core study',subject:'English',mins:60},
{id:'3',time:'11:35',end:'12:00',task:'Math previous chapter revision',subject:'Math',mins:25},
{id:'4',time:'12:00',end:'13:30',task:'Math core chapter study',subject:'Math',mins:90},
{id:'5',time:'13:30',end:'14:00',task:'Lunch',subject:'Break',mins:0,break:true},
{id:'6',time:'14:00',end:'14:15',task:'Physics previous day / chapter revision',subject:'Physics',mins:15},
{id:'7',time:'14:15',end:'16:00',task:'Physics core study',subject:'Physics',mins:105},
{id:'8',time:'16:00',end:'16:20',task:'Chemistry previous chapter / day revision',subject:'Chemistry',mins:20},
{id:'9',time:'16:20',end:'18:00',task:'Chemistry core study',subject:'Chemistry',mins:100},
{id:'10',time:'18:20',end:'18:30',task:'Revision',subject:'Revision',mins:10},
{id:'11',time:'18:30',end:'19:30',task:'Physics Chapter 3',subject:'Physics',mins:60}
];
function load(){try{let x=JSON.parse(localStorage.getItem(KEY)||'null');if(x?.items?.length)return x;let old=JSON.parse(localStorage.getItem('discipline_ai_day_routine_v4')||localStorage.getItem('discipline_ai_day_routine_v3')||localStorage.getItem('discipline_ai_day_routine_v2')||'null');return{items:old?.items?.length?old.items:defaults,done:old?.done||{},history:old?.history||{}}}catch{return{items:defaults,done:{},history:{}}}}
function save(x){localStorage.setItem(KEY,JSON.stringify(x))}
function stats(x,k){x.done=x.done||{};x.done[k]=x.done[k]||{};const a=x.items.filter(i=>!i.break),d=a.filter(i=>x.done[k][i.id]).length,p=a.reduce((n,i)=>n+(+i.mins||0),0),s=a.filter(i=>x.done[k][i.id]).reduce((n,i)=>n+(+i.mins||0),0);let ts=[];try{ts=JSON.parse(localStorage.getItem('discipline_ai_tests_v4')||'[]').filter(t=>String(t.date||'').slice(0,10)===k)}catch{}return{done:d,total:a.length,planned:p,study:s,pct:a.length?Math.round(d/a.length*100):0,tests:ts,avg:ts.length?Math.round(ts.reduce((n,t)=>n+(+t.percent||0),0)/ts.length):0}}
function record(x,k){const s=stats(x,k);x.history=x.history||{};x.history[k]={date:k,items:{...x.done[k]},studyMins:s.study,plannedMins:s.planned,completed:s.done,total:s.total,progress:s.pct}}
function history(x){const today=keyOf(),arr=Array.from({length:31},(_,i)=>addDays(today,-i));return `<div class="history-list">${arr.map(k=>{const s=stats(x,k);return `<div class="history-row ${k===today?'current':''}"><div><b>${esc(pretty(k))}${k===today?' • Today':''}</b><small>${s.done}/${s.total} blocks • ${s.study} min study</small></div><div class="history-right"><b>${s.pct}%</b><div class="mini-progress"><i style="width:${s.pct}%"></i></div><small>${s.tests.length} test${s.tests.length===1?'':'s'} • avg ${s.avg}%</small></div></div>`}).join('')}</div>`}
function render(){const x=load(),k=keyOf();x.done=x.done||{};x.done[k]=x.done[k]||{};record(x,k);save(x);const s=stats(x,k),now=new Date(),clock=now.toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',second:'2-digit'}),rows=x.items.map(i=>{const state=blockState(i),locked=state!=='live'||i.break,done=!!x.done[k][i.id];return `<div class="routine-item ${i.break?'break-item ':''}${done?'done ':''}${state}"><label class="routine-check"><input type="checkbox" data-routine="${esc(i.id)}" ${done?'checked':''} ${locked?'disabled':''}><span></span></label><div class="routine-time">${time12(i.time)}–${time12(i.end)}</div><div class="routine-info"><b>${esc(i.task)}</b><small>${esc(i.subject)}${i.mins?' • '+i.mins+' min':''}${i.break?' • Break':' • '+stateText(state)}</small></div></div>`}).join('');return page('My Day Routine','Real-time routine • checkbox sirf scheduled time ke andar active rahega.',`<div class="routine-hero card"><div><div class="eyebrow">${esc(pretty(k))}</div><h2 style="margin:4px 0">📅 My Daily Study Routine</h2><p class="muted">🕒 <b>Live time: ${clock}</b></p><p class="muted">⏱️ <b>Rule:</b> block start hone se pehle aur block khatam hone ke baad checkbox locked rahega. Example: 10:00–12:00 wala block 1:00 PM par fill nahi ho sakta.</p></div><div class="routine-circle" style="--routine-p:${s.pct}%"><strong>${s.pct}%</strong><span>Today</span></div></div><div class="grid stats routine-stats"><div class="card stat"><span>Study Blocks</span><b>${s.done}/${s.total}</b></div><div class="card stat"><span>Study Completed</span><b>${s.study} min</b></div><div class="card stat"><span>Planned Study</span><b>${s.planned} min</b></div><div class="card stat"><span>Tests Today</span><b>${s.tests.length} • ${s.avg}%</b></div></div><div class="card"><div class="section"><div><h3>📅 Today's Schedule</h3><p class="muted" style="margin:3px 0">🟢 Live = checkbox active • 🔒 Not started • ⏰ Time over</p></div><button type="button" class="btn secondary" id="editRoutine">✏️ Edit Daily Template</button></div><div class="routine-list">${rows}</div></div><div class="card routine-summary"><div class="section"><div><h3>📊 Today's Progress</h3><p class="muted">${s.done} of ${s.total} study blocks completed</p></div><b>${s.pct}%</b></div><div class="progress"><i style="width:${s.pct}%"></i></div><p><b>${s.study} min</b> study completed out of <b>${s.planned} min</b> planned.</p></div><div class="card"><div class="section"><div><h3>📈 Date-wise Progress History</h3><p class="muted">Last 31 days — har date ka record separately saved.</p></div></div>${history(x)}</div>`}
function openRoutine(){const p=document.getElementById('pages');if(!p)return false;p.innerHTML=render();bind();return true}
window.openRoutine=openRoutine;
function bind(){const x=load(),k=keyOf();x.done=x.done||{};x.done[k]=x.done[k]||{};document.querySelectorAll('[data-routine]').forEach(c=>c.onchange=()=>{const item=x.items.find(i=>String(i.id)===String(c.dataset.routine));if(!item)return;const state=blockState(item);if(state!=='live'){c.checked=!!x.done[k][item.id];toast(state==='upcoming'?'⏳ Ye study block abhi start nahi hua hai.':'⏰ Is study block ka time khatam ho gaya hai.');return}if(c.checked)x.done[k][c.dataset.routine]=true;else delete x.done[k][c.dataset.routine];record(x,k);save(x);openRoutine()});document.getElementById('editRoutine')?.addEventListener('click',editor)}
function editor(){const x=load(),m=document.createElement('div');m.className='routine-modal';m.innerHTML=`<div class="routine-modal-box"><div class="section"><div><h2 style="margin:0">✏️ Daily Routine Template</h2><p class="muted">Change karoge to future days me same routine rahega; purane dates ka progress safe rahega.</p></div><button class="btn ghost" id="cr">✕</button></div><div id="er">${x.items.map(i=>`<div class="routine-edit-row" data-id="${esc(i.id)}"><input class="input rt-time" type="time" value="${esc(i.time)}"><input class="input rt-end" type="time" value="${esc(i.end)}"><input class="input rt-task" value="${esc(i.task)}"><input class="input rt-sub" value="${esc(i.subject)}"><input class="input rt-mins" type="number" min="0" value="${+i.mins||0}"><label><input class="rt-break" type="checkbox" ${i.break?'checked':''}> Break</label><button class="btn ghost rt-del">🗑️</button></div>`).join('')}</div><div class="actions"><button class="btn" id="sr">💾 Save Daily Template</button></div></div>`;document.body.appendChild(m);m.querySelector('#cr').onclick=()=>m.remove();m.querySelectorAll('.rt-del').forEach(b=>b.onclick=()=>b.closest('.routine-edit-row').remove());m.querySelector('#sr').onclick=()=>{x.items=[...m.querySelectorAll('.routine-edit-row')].map(r=>({id:r.dataset.id,time:r.querySelector('.rt-time').value,end:r.querySelector('.rt-end').value,task:r.querySelector('.rt-task').value||'Study Block',subject:r.querySelector('.rt-sub').value||'Study',mins:r.querySelector('.rt-break').checked?0:(+r.querySelector('.rt-mins').value||30),break:r.querySelector('.rt-break').checked}));save(x);m.remove();openRoutine();toast('Daily routine template saved. ✅')}}
function ensureNav(){const n=document.querySelector('.nav');if(!n)return false;if(!n.querySelector('[data-page="routine"]')){const b=document.createElement('button');b.type='button';b.dataset.page='routine';b.innerHTML='📅&nbsp; My Day Routine';b.onclick=openRoutine;n.appendChild(b)}return true}
const st=document.createElement('style');st.textContent=`.routine-hero{display:flex;justify-content:space-between;align-items:center;gap:18px;background:linear-gradient(135deg,#111a31,#0b1221)}.routine-circle{width:120px;height:120px;min-width:120px;border-radius:50%;display:grid;place-items:center;position:relative;background:conic-gradient(var(--p) var(--routine-p),#27314a 0)}.routine-circle:after{content:'';position:absolute;inset:9px;border-radius:50%;background:#0c1425}.routine-circle strong{position:relative;z-index:1;font-size:28px}.routine-circle span{position:absolute;z-index:1;font-size:10px;color:var(--muted);margin-top:48px}.routine-list,.history-list{display:grid;gap:8px}.routine-item{display:grid;grid-template-columns:30px 125px 1fr;align-items:center;gap:8px;padding:12px;border-radius:12px;border:1px solid rgba(255,255,255,.08);background:rgba(255,255,255,.02)}.routine-item.done{opacity:.62}.routine-item.done .routine-info b{text-decoration:line-through}.routine-item.upcoming,.routine-item.expired{opacity:.72}.routine-item.live{border-color:rgba(36,209,139,.35);box-shadow:0 0 0 1px rgba(36,209,139,.08)}.routine-check input{display:none}.routine-check input:disabled+span{cursor:not-allowed;opacity:.4}.routine-check span{display:block;width:20px;height:20px;border:2px solid #68738d;border-radius:6px}.routine-check input:checked+span{background:var(--p);border-color:var(--p);position:relative}.routine-check input:checked+span:after{content:'✓';position:absolute;left:3px;top:-3px;font-weight:900}.routine-time{font-weight:800;font-size:12px;white-space:nowrap}.routine-info small,.history-row small{display:block;color:var(--muted);margin-top:4px}.history-row{display:flex;justify-content:space-between;gap:15px;align-items:center;padding:12px;border:1px solid rgba(255,255,255,.08);border-radius:12px}.history-row.current{border-color:rgba(155,142,255,.35)}.history-right{text-align:right;min-width:155px}.mini-progress{height:6px;background:#202a40;border-radius:99px;overflow:hidden;margin:5px 0}.mini-progress i{display:block;height:100%;background:linear-gradient(90deg,var(--p),#2dd4ff);border-radius:99px}.routine-modal{position:fixed;inset:0;background:rgba(0,0,0,.75);z-index:10000;display:flex;align-items:center;justify-content:center;padding:15px}.routine-modal-box{width:min(1050px,100%);max-height:90vh;overflow:auto;background:#0c1425;border:1px solid rgba(255,255,255,.12);border-radius:18px;padding:18px}.routine-edit-row{display:grid;grid-template-columns:95px 95px 1.5fr 1fr 75px 70px 45px;gap:7px;margin-bottom:8px;align-items:center}@media(max-width:700px){.routine-hero{align-items:flex-start}.routine-circle{width:95px;height:95px;min-width:95px}.routine-item{grid-template-columns:30px 125px 1fr}.history-row{align-items:flex-start}.history-right{min-width:105px}.routine-edit-row{grid-template-columns:1fr 1fr}.routine-edit-row .rt-task,.routine-edit-row .rt-sub{grid-column:span 2}}`;document.head.appendChild(st);
const oldShow=typeof show==='function'?show:null;if(oldShow)show=function(id){if(id==='routine')return openRoutine();return oldShow(id)};
let lastMinute=-1;function refreshClock(){ensureNav();const p=document.getElementById('pages');const routineVisible=!!p?.querySelector('.routine-hero');const minute=minutesNow();if(routineVisible&&minute!==lastMinute){lastMinute=minute;openRoutine()}}
const observer=new MutationObserver(()=>ensureNav());observer.observe(document.body,{childList:true,subtree:true});setTimeout(ensureNav,100);setTimeout(ensureNav,500);setTimeout(ensureNav,1200);setInterval(refreshClock,1000);
})();