(()=>{'use strict';
const DB='discipline_ai_study_library_v1',STORE='resources';
const SUBJECTS={Physics:['Electric Charges and Fields','Electrostatic Potential and Capacitance','Current Electricity','Moving Charges and Magnetism','Magnetism and Matter','Electromagnetic Induction','Alternating Current','Electromagnetic Waves','Ray Optics and Optical Instruments','Wave Optics','Dual Nature of Radiation and Matter','Atoms','Nuclei','Semiconductor Electronics'],Chemistry:['Solutions','Electrochemistry','Chemical Kinetics','d- and f-Block Elements','Coordination Compounds','Haloalkanes and Haloarenes','Alcohols, Phenols and Ethers','Aldehydes, Ketones and Carboxylic Acids','Amines','Biomolecules, Polymers and Chemistry in Everyday Life'],Mathematics:['Relations and Functions','Inverse Trigonometric Functions','Matrices','Determinants','Continuity and Differentiability','Application of Derivatives','Integrals','Application of Integrals','Differential Equations','Vector Algebra','Three Dimensional Geometry','Linear Programming','Probability'],English:['Indian Civilization and Culture','Bharat is My Home','A Pinch of Snuff','I Have a Dream','Ideas that have Helped Mankind','The Artist','A Child Born','How Free is the Press','The Earth','India Through a Traveller’s Eyes','A Marriage Proposal','Sweetest Love I do not Goe','Song of Myself','Now the Leaves are Falling Fast','An Epitaph','The Soldier','Macavity: The Mystery Cat','Fire-Hymn','Snake','My Grandmother’s House'],Hindi:['बातचीत','उसने कहा था','संपूर्ण क्रांति','अर्थनारीश्वर','रोज','एक लेख और एक पत्र','ओ सदानीरा','सिपाही की माँ','प्रेम और समाज','जूठन','हँसते हुए मेरा अकेलापन','तिरिछ','शिक्षा','कड़बक','पद — सूरदास','पद — तुलसीदास','छप्पय','कवित्त','तुमुल कोलाहल कलह में','पुत्र-वियोग','उषा','जन-जन का चेहरा एक','अधिनायक','प्यारे नन्हें बेटे को','हार-जीत','गाँव का घर','रस्सी का टुकड़ा','क्लर्क की मौत','पैगनी'],English Grammar:['Tenses','Narration (Direct and Indirect Speech)','Voice (Active and Passive)','Modals','Articles','Prepositions','Conjunctions','Subject-Verb Agreement','Parts of Speech','Transformation of Sentences','Question Tags','Adjective','Adverb']};
let db;
function open(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:'id',autoIncrement:true});r.onsuccess=()=>{db=r.result;res(db)};r.onerror=()=>rej(r.error)})}
async function all(){await open();return new Promise((res,rej)=>{const q=db.transaction(STORE,'readonly').objectStore(STORE).getAll();q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function put(x){await open();return new Promise((res,rej)=>{const q=db.transaction(STORE,'readwrite').objectStore(STORE).add(x);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function del(id){await open();db.transaction(STORE,'readwrite').objectStore(STORE).delete(Number(id))}
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random()}
function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m])}
function ui(){const root=document.getElementById('pages');if(!root||document.getElementById('studyLibrary'))return;const card=document.createElement('div');card.id='studyLibrary';card.className='card';card.style.marginTop='16px';card.innerHTML='<div class="section"><div><h3>📚 Class Library</h3><p class="muted">Chapter-wise YouTube lectures + PDFs, saved in this browser.</p></div><button class="btn" id="libOpen">Open Library</button></div>';root.appendChild(card);document.getElementById('libOpen').onclick=openPage}
async function openPage(){const p=document.getElementById('pages');if(!p)return;const items=await all();p.innerHTML='<div class="card"><div class="section"><div><h2>📚 Class Library</h2><p class="muted">Subject → Chapter → Lectures / PDFs</p></div><button class="btn secondary" id="libBack">Dashboard</button></div><div class="card"><h3>➕ Add Lecture / PDF</h3><div class="grid"><select id="libSub">'+Object.keys(SUBJECTS).map(s=>'<option>'+esc(s)+'</option>').join('')+'</select><select id="libChap"></select><select id="libType"><option value="youtube">YouTube Lecture</option><option value="pdf">PDF / Notes</option></select></div><input id="libTitle" class="input" placeholder="Title"><input id="libUrl" class="input" placeholder="YouTube URL (for lecture)"><input id="libFile" type="file" accept=".pdf,application/pdf" style="display:none"><button class="btn" id="libSave">Save Resource</button><p class="muted">PDF files stay in browser IndexedDB. Use Backup to keep a copy if browser storage is cleared.</p></div><div id="libList"></div><div class="card"><button class="btn secondary" id="libBackup">⬇️ Backup Library</button><input id="libRestore" type="file" accept=".json" style="display:none"><button class="btn secondary" id="libRestoreBtn">⬆️ Restore Backup</button></div></div>';
const sub=document.getElementById('libSub'),chap=document.getElementById('libChap'),type=document.getElementById('libType'),file=document.getElementById('libFile');function fill(){chap.innerHTML=(SUBJECTS[sub.value]||[]).map(x=>'<option>'+esc(x)+'</option>').join('')}fill();sub.onchange=fill;type.onchange=()=>{file.style.display=type.value==='pdf'?'block':'none';document.getElementById('libUrl').style.display=type.value==='youtube'?'block':'none'};type.onchange();
document.getElementById('libSave').onclick=async()=>{const title=document.getElementById('libTitle').value.trim()||'Untitled';const base={subject:sub.value,chapter:chap.value,title,type:type.value,createdAt:new Date().toISOString(),uid:uid()};if(type.value==='youtube'){const u=document.getElementById('libUrl').value.trim();if(!u)return alert('YouTube URL add karo.');base.url=u}else{if(!file.files[0])return alert('PDF choose karo.');const f=file.files[0];base.fileName=f.name;base.mime=f.type;base.blob=f}await put(base);await openPage()};
document.getElementById('libBack').onclick=()=>document.querySelector('[data-page="dashboard"]')?.click();document.getElementById('libBackup').onclick=async()=>{const a=await all();const clean=a.map(x=>({...x,blob:undefined}));const b=new Blob([JSON.stringify(clean)],{type:'application/json'}),u=URL.createObjectURL(b),z=document.createElement('a');z.href=u;z.download='discipline-ai-library-backup.json';z.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};document.getElementById('libRestoreBtn').onclick=()=>document.getElementById('libRestore').click();document.getElementById('libRestore').onchange=async e=>{try{const a=JSON.parse(await e.target.files[0].text());for(const x of a)await put({...x,id:undefined});await openPage()}catch{alert('Backup file invalid.')}};
const grouped={};items.forEach(x=>(grouped[x.subject]??={})[x.chapter]??=[]);items.forEach(x=>{grouped[x.subject][x.chapter].push(x)});document.getElementById('libList').innerHTML=Object.entries(grouped).map(([s,ch])=>'<div class="card"><h3>'+esc(s)+'</h3>'+Object.entries(ch).map(([c,arr])=>'<details><summary>'+esc(c)+' ('+arr.length+')</summary>'+arr.map(x=>x.type==='youtube'?'<div class="chapter"><span>▶️ '+esc(x.title)+'</span><a class="btn secondary" target="_blank" rel="noopener" href="'+esc(x.url)+'">Watch</a></div>':'<div class="chapter"><span>📄 '+esc(x.title)+'<small class="muted" style="display:block">'+esc(x.fileName)+'</small></span><button class="btn secondary" data-pdf="'+x.id+'">Open PDF</button></div>').join('')+'</details>').join('')+'</div>').join('')||'<div class="empty">No resources yet. Add your first lecture or PDF.</div>';document.querySelectorAll('[data-pdf]').forEach(b=>b.onclick=async()=>{const x=items.find(v=>v.id==b.dataset.pdf);if(!x?.blob)return;const u=URL.createObjectURL(x.blob);window.open(u,'_blank');setTimeout(()=>URL.revokeObjectURL(u),60000)})}
const ob=new MutationObserver(ui);ob.observe(document.body,{childList:true,subtree:true});setTimeout(ui,700);window.DisciplineLibrary={open:openPage,subjects:SUBJECTS};
})();