(() => {
  const KEY='discipline_ai_v1';
  const subjects={
    Physics:['Electric Charges and Fields','Electrostatic Potential and Capacitance','Current Electricity','Moving Charges and Magnetism','Magnetism and Matter','Electromagnetic Induction','Alternating Current','Electromagnetic Waves','Ray Optics and Optical Instruments','Wave Optics','Dual Nature of Radiation and Matter','Atoms','Nuclei','Semiconductor Electronics'],
    Chemistry:['Solutions','Electrochemistry','Chemical Kinetics','d- and f-Block Elements','Coordination Compounds','Haloalkanes and Haloarenes','Alcohols, Phenols and Ethers','Aldehydes, Ketones and Carboxylic Acids','Amines','Biomolecules, Polymers and Chemistry in Everyday Life'],
    Mathematics:['Relations and Functions','Inverse Trigonometric Functions','Matrices','Determinants','Continuity and Differentiability','Application of Derivatives','Integrals','Application of Integrals','Differential Equations','Vector Algebra','Three Dimensional Geometry','Linear Programming','Probability']
  };
  const routine=[['10:00–10:30','English previous chapter revision','English',30],['10:30–11:30','English core study','English',60],['11:35–12:00','Math previous chapter revision','Math',25],['12:00–13:30','Math core chapter study','Math',90],['13:30–14:00','Lunch','Break',0],['14:00–14:15','Physics previous day / chapter revision','Physics',15],['14:15–16:00','Physics core study','Physics',105],['16:00–16:20','Chemistry previous chapter / day revision','Chemistry',20],['16:20–18:00','Chemistry core study','Chemistry',100],['18:20–18:30','Revision','Revision',10],['18:30–19:30','Physics Chapter 3','Physics',60]];
  const menu=[
    ['dashboard','🏠','Dashboard','Study command center'],['mock','📝','Mock Test','Objective test flow'],['pyq','📷','PYQ Tests','Upload, extract and test'],['history','🕘','PYQ History','Previous PYQ attempts'],['tests','✅','My Tests','Completed test records'],['wrong','❌','Wrong Questions','Review and retry'],['weak','🎯','Weak Topics','Weak-area detection'],['practice','⚡','Fresh Practice','Practice weak areas'],['syllabus','📚','Syllabus','Physics, Chemistry, Mathematics'],['progress','📊','Progress','Overall performance'],['settings','⚙️','Settings','Preferences'],['ai','🤖','AI Tutor','Chat with study AI'],['routine','🗓️','Daily Study Routine','Live schedule and 31-day history']
  ];
  let state=JSON.parse(localStorage.getItem(KEY)||'{"page":"dashboard","tests":[],"routine":{},"settings":{"timer":30}}');
  const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
  const root=document.getElementById('root');
  const toast=(m)=>{let t=document.getElementById('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)};
  const go=p=>{state.page=p;save();render();document.querySelector('.sidebar')?.classList.remove('open');window.scrollTo(0,0)};
  const nav=()=>menu.map(x=>`<button class="${state.page===x[0]?'active':''}" data-page="${x[0]}"><span>${x[1]}</span>${x[2]}</button>`).join('');
  const shell=content=>`<div class="app"><aside class="sidebar"><div class="brand"><div class="brand-icon">⚡</div><div>Discipline AI<small class="muted" style="display:block;font-size:10px">Class 12 Science</small></div></div><nav class="nav">${nav()}</nav><div class="profile-mini"><div class="avatar">S</div><div><b>Sajid Khan</b><small class="muted" style="display:block">Bihar Board • Science</small></div></div></aside><main class="main"><div class="top"><div><button class="mobile-menu" id="mobile">☰</button></div><div class="muted">Class 12 • Bihar Board</div></div>${content}</main><div id="toast" class="toast"></div></div>`;
  function dashboard(){const total=state.tests.length,avg=total?Math.round(state.tests.reduce((a,b)=>a+b.pct,0)/total):0;return `<div class="hero card"><div><div class="eyebrow">Study Command Center</div><h2>Welcome back, Sajid 👋</h2><p>Focused preparation for Class 12 Science.</p></div><div class="pill">v1 • New Website</div></div><div class="grid stats"><div class="card stat"><small>Tests</small><strong>${total}</strong><span class="muted">completed</span></div><div class="card stat"><small>Average</small><strong>${avg}%</strong><span class="muted">score</span></div><div class="card stat"><small>PYQ</small><strong>${state.tests.filter(t=>t.type==='PYQ').length}</strong><span class="muted">attempts</span></div><div class="card stat"><small>Routine</small><strong>${Object.values(state.routine).filter(Boolean).length}</strong><span class="muted">blocks done</span></div></div><div class="section"><h3>Quick Actions</h3></div><div class="grid menus">${menu.filter(x=>['mock','pyq','wrong','weak','practice','syllabus'].includes(x[0])).map(x=>`<button class="card menu-card" data-page="${x[0]}"><div class="icon">${x[1]}</div><h3>${x[2]}</h3><p>${x[3]}</p></button>`).join('')}</div><div class="grid cols" style="margin-top:15px"><div class="card"><div class="section"><h3>Daily Study Routine</h3><button class="btn secondary" data-page="routine">Open</button></div><p class="muted">Schedule → live block → completion → history.</p><div class="bar"><i style="width:${Math.min(100,Object.values(state.routine).filter(Boolean).length/routine.filter(r=>r[3]>0).length*100||0)}%"></i></div></div><div class="card"><div class="section"><h3>AI Tutor</h3><button class="btn" data-page="ai">Open AI</button></div><p class="muted">Ask questions and keep your local chat history.</p></div></div>`}
  function routinePage(){const done=Object.values(state.routine).filter(Boolean).length,work=routine.filter(r=>r[3]>0).length;return `<div class="eyebrow">Study System</div><h1 class="title">Daily Study Routine</h1><p class="muted">Live, upcoming and completed study blocks.</p><div class="card"><div class="section"><h3>Today</h3><span class="pill">${done}/${work} study blocks completed</span></div>${routine.map((r,i)=>`<div class="routine-row ${r[2]==='Break'?'expired':''}"><b>${r[0]}</b><div><strong>${r[1]}</strong><small class="muted" style="display:block">${r[2]}</small></div><span class="pill">${r[3]} min</span><div class="routine-check">${r[3]?`<input class="check routine" type="checkbox" data-i="${i}" ${state.routine[i]?'checked':''}>`:''}</div></div>`).join('')}</div><div class="card" style="margin-top:15px"><div class="section"><h3>31-Day History</h3><span class="muted">Current browser</span></div><p class="muted">History stores completed count, study minutes and percentage for the routine.</p><div class="bar"><i style="width:${Math.min(100,done/work*100||0)}%"></i></div></div>`}
  function syllabus(){return `<div class="eyebrow">Class 12 Science</div><h1 class="title">Syllabus</h1><p class="muted">Select a subject and chapter to continue to chapter-specific practice.</p><div class="card">${Object.entries(subjects).map(([s,chs])=>`<details class="subject"><summary>📘 ${s} <span class="muted">• ${chs.length} chapters</span></summary><div class="chapters">${chs.map((c,i)=>`<div class="chapter"><span>${i+1}. ${c}</span><button class="btn secondary chapter-btn" data-subject="${s}" data-chapter="${c}">Practice</button></div>`).join('')}</div></details>`).join('')}</div>`}
  function testPage(type='Mock'){return `<div class="test-wrap"><div class="eyebrow">${type} Test</div><h1 class="title">${type} Test</h1><div class="card"><div class="form"><div class="row"><label><span class="label">Subject</span><select id="tSubject" class="select"><option>Physics</option><option>Chemistry</option><option>Mathematics</option></select></label><label><span class="label">Chapter</span><select id="tChapter" class="select">${subjects.Physics.map(c=>`<option>${c}</option>`).join('')}</select></label></div><div class="row"><label><span class="label">Timer (1–180 min)</span><input id="timer" class="input" type="number" min="1" max="180" value="${state.settings.timer||30}"></label><label><span class="label">Question count</span><select id="count" class="select"><option>10</option><option>20</option><option>30</option><option>50</option><option>100</option><option>All</option></select></label></div><p class="muted">${type==='PYQ'?'Upload a clear PYQ photo/PDF or enter questions manually. AI extraction will use the server endpoint.':'Start with the objective test engine. You can add a full question set in the next step.'}</p>${type==='PYQ'?`<input id="pyqFiles" class="input" type="file" accept="image/*,.pdf" multiple><textarea id="manual" class="textarea" placeholder="Optional: paste PYQ questions here..."></textarea>`:''}<div class="actions"><button class="btn" id="startTest">${type==='PYQ'?'Extract PYQ & Start':'Start Test'}</button><button class="btn secondary" data-page="dashboard">Cancel</button></div><div id="testMsg" class="muted"></div></div></div></div>`}
  function records(title,filter){let arr=state.tests.filter(filter);return `<div class="eyebrow">Performance</div><h1 class="title">${title}</h1><div class="card">${arr.length?`<table class="table"><thead><tr><th>Date</th><th>Type</th><th>Subject</th><th>Score</th><th>Accuracy</th></tr></thead><tbody>${arr.slice().reverse().map(t=>`<tr><td>${new Date(t.date).toLocaleDateString()}</td><td>${t.type}</td><td>${t.subject}</td><td>${t.score}/${t.total}</td><td>${t.pct}%</td></tr>`).join('')}</tbody></table>`:'<div class="empty">No attempts yet. Start a test to build your history.</div>'}</div>`}
  function generic(title,icon,text){return `<div class="eyebrow">Study Tools</div><h1 class="title">${icon} ${title}</h1><div class="card"><p>${text}</p><div class="actions"><button class="btn" data-page="mock">Start Mock Test</button><button class="btn secondary" data-page="syllabus">Open Syllabus</button></div></div>`}
  function progress(){const n=state.tests.length,avg=n?Math.round(state.tests.reduce((a,b)=>a+b.pct,0)/n):0;return `<div class="eyebrow">Analytics</div><h1 class="title">Progress</h1><div class="grid stats"><div class="card stat"><small>Total tests</small><strong>${n}</strong></div><div class="card stat"><small>Average accuracy</small><strong>${avg}%</strong></div><div class="card stat"><small>Best score</small><strong>${n?Math.max(...state.tests.map(t=>t.pct)):0}%</strong></div><div class="card stat"><small>Routine blocks</small><strong>${Object.values(state.routine).filter(Boolean).length}</strong></div></div><div class="card"><h3>Overall Progress</h3><p class="muted">Performance is calculated from completed tests stored in this browser.</p><div class="bar"><i style="width:${avg}%"></i></div></div>`}
  function settings(){return `<div class="eyebrow">Configuration</div><h1 class="title">Settings</h1><div class="card"><div class="form"><label><span class="label">Default timer (minutes)</span><input id="setTimer" class="input" type="number" min="1" max="180" value="${state.settings.timer||30}"></label><div class="actions"><button class="btn" id="saveSettings">Save Settings</button><button class="btn danger" id="clearData">Clear local website data</button></div></div></div>`}
  function ai(){return `<div class="eyebrow">AI Study Assistant</div><h1 class="title">AI Tutor</h1><div class="card chat"><div id="messages" class="messages"><div class="msg bot">Hi! I’m your study AI. Ask me about Physics, Chemistry, Mathematics, revision or test analysis.</div>${(state.chat||[]).map(m=>`<div class="msg ${m.role==='user'?'user':'bot'}">${escapeHtml(m.content)}</div>`).join('')}</div><form id="chatForm" class="chat-form"><textarea id="chatInput" class="textarea" placeholder="Ask your study question..."></textarea><button class="btn" type="submit">Send</button></form></div>`}
  function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function page(){switch(state.page){case'routine':return routinePage();case'syllabus':return syllabus();case'mock':return testPage('Mock');case'pyq':return testPage('PYQ');case'history':return records('PYQ History',t=>t.type==='PYQ');case'tests':return records('My Tests',()=>true);case'progress':return progress();case'settings':return settings();case'ai':return ai();case'wrong':return generic('Wrong Questions','❌','Wrong-answer review and retry flow. Test results will feed this section as the question engine is expanded.');case'weak':return generic('Weak Topics','🎯','Weak-area detection grouped by subject/chapter will use saved test results.');case'practice':return generic('Fresh Practice','⚡','Practice will be generated from saved weak areas and previous mistakes.');default:return dashboard()}}
  function bind(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>go(b.dataset.page));document.getElementById('mobile')?.addEventListener('click',()=>document.querySelector('.sidebar').classList.toggle('open'));document.querySelectorAll('.routine').forEach(c=>c.onchange=()=>{state.routine[c.dataset.i]=c.checked;save();render()});document.querySelectorAll('.chapter-btn').forEach(b=>b.onclick=()=>{state.page='pyq';state.prefill={subject:b.dataset.subject,chapter:b.dataset.chapter};save();render()});
    const sub=document.getElementById('tSubject'),ch=document.getElementById('tChapter');if(sub&&ch){sub.onchange=()=>{ch.innerHTML=(subjects[sub.value]||[]).map(c=>`<option>${c}</option>`).join('')};if(state.prefill){sub.value=state.prefill.subject;sub.onchange();ch.value=state.prefill.chapter;delete state.prefill;save()}}
    document.getElementById('startTest')?.addEventListener('click',async()=>{const msg=document.getElementById('testMsg'),type=state.page==='pyq'?'PYQ':'Mock',subject=sub?.value||'Physics',chapter=ch?.value||subjects.Physics[0];state.settings.timer=Math.max(1,Math.min(180,Number(document.getElementById('timer')?.value)||30));save();if(type==='PYQ'){const files=[...(document.getElementById('pyqFiles')?.files||[])];const manual=document.getElementById('manual')?.value||'';if(!files.length&&!manual.trim()){msg.textContent='Please add a PYQ photo/PDF or manual questions.';return}msg.textContent='Uploading source and extracting MCQs...';try{const encoded=[];for(const f of files){encoded.push({name:f.name,mimeType:f.type,data:(await fileToBase64(f)).split(',')[1]})}const r=await fetch('/api/pyq-test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({files:encoded,text:manual,subject,chapter})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Extraction failed');sessionStorage.setItem('discipline_ai_pyq_questions',JSON.stringify(d.questions));msg.textContent=`Extracted ${d.questions.length} MCQs successfully. Test engine hookup is next.`;toast('PYQ extraction successful');}catch(e){msg.textContent=e.message;toast('PYQ extraction failed')}}else{toast('Mock test engine shell is ready — question bank hookup is next.')}});
    document.getElementById('saveSettings')?.addEventListener('click',()=>{state.settings.timer=Math.max(1,Math.min(180,Number(document.getElementById('setTimer').value)||30));save();toast('Settings saved')});document.getElementById('clearData')?.addEventListener('click',()=>{if(confirm('Clear this website v1 local data?')){localStorage.removeItem(KEY);state={page:'dashboard',tests:[],routine:{},settings:{timer:30}};render();toast('Local data cleared')}});
    document.getElementById('chatForm')?.addEventListener('submit',async e=>{e.preventDefault();const input=document.getElementById('chatInput'),text=input.value.trim();if(!text)return;state.chat=state.chat||[];state.chat.push({role:'user',content:text});input.value='';save();render();const messages=document.getElementById('messages');messages.scrollTop=messages.scrollHeight;try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:state.chat})});const d=await r.json();if(!r.ok)throw new Error(d.error||'AI request failed');state.chat.push({role:'assistant',content:d.reply||'No response'});save();render()}catch(err){state.chat.push({role:'assistant',content:'AI error: '+err.message});save();render()}});
  }
  function fileToBase64(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
  function render(){root.innerHTML=shell(page());bind()}
  render();
})();
